version: "3.9"

services:
  app:
    container_name: project-database-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      mysql:
        condition: service_healthy
      mongodb:
        condition: service_started
    command: sh -c "bun install && bunx prisma db push && bun run app/scripts/seedProducts.ts && (bun dev & bunx prisma studio --hostname 0.0.0.0) && wait"
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database_project
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data: