import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster
          position="bottom-right"
          toastOptions={{
            style: {
              background: "#171717",
              border: "1px solid #2a2a2a",
              color: "#ffffff",
              fontFamily: "var(--font-geist-sans)",
              fontSize: "13px",
              letterSpacing: "0.05em",
              borderRadius: "2px",
            },
            classNames: {
              success: "!border-l-2 !border-l-[#C9A84C]",
              error: "!border-l-2 !border-l-red-500",
              warning: "!border-l-2 !border-l-yellow-500",
            },
          }}
        />
      </body>
    </html>
  );
}
